This notebook tests data queries for my Spyre app.

In [2]:
import pandas as pd
provinces = pd.read_csv('../lab1/ukr_provinces.csv', comment='#', sep='[, ]+', engine='python')
provinces

,CountryCode,provinceID,minLat,minLon,maxLat,maxLon,newID,province_name
0,UKR,1,48.4658,29.6201,50.2095,32.9217,22,Cherkasy
1,UKR,2,50.3263,30.4749,52.3750,33.5088,24,Chernihiv
2,UKR,3,47.7299,24.8985,48.6767,27.5337,23,Chernivtsi
3,UKR,4,44.3821,32.4623,46.1905,36.6457,25,Crimea
4,UKR,5,47.4224,32.9624,49.1688,36.9234,3,Dnipropetrovsk
5,UKR,6,46.8547,36.5451,49.2586,39.0730,4,Donetsk
6,UKR,7,47.7256,23.5408,49.5503,25.6406,8,Ivano-Frankivsk
7,UKR,8,48.5145,34.8923,50.4649,38.0916,19,Kharkiv
8,UKR,9,45.9012,31.5029,47.5770,35.1345,20,Kherson
9,UKR,10,48.4516,26.1233,50.5936,27.9138,21,Khmelnytskyy
10,UKR,11,49.1833,29.2782,51.5291,32.1777,9,Kiev
11,UKR,12,50.2222,30.2436,50.5990,30.8177,26,Kiev(City)
12,UKR,13,47.7474,29.7669,49.2203,33.9350,10,Kirovohrad
13,UKR,14,47.8197,37.8543,50.0859,40.2181,11,Luhansk
14,UKR,15,48.7197,22.6674,50.6624,25.4084,12,Lviv
15,UKR,16,46.6071,30.2248,48.2243,33.1872,13,Mykolayiv
16,UKR,17,45.2046,28.1966,48.2608,31.3259,14,Odessa
17,UKR,18,48.7129,32.1130,50.5330,35.5214,15,Poltava
18,UKR,19,50.0053,25.0927,51.9615,27.7233,16,Rivne
19,UKR,20,44.3821,33.3637,44.8442,33.9267,27,Sevastopol
20,UKR,21,50.0999,32.9896,52.3600,35.6936,17,Sumy
21,UKR,22,48.5085,24.6968,50.2727,26.4382,18,Ternopil
22,UKR,23,47.9043,22.1404,49.0956,24.6196,6,Transcarpathia
23,UKR,24,48.0641,27.3740,49.8979,30.0414,1,Vinnytsya
24,UKR,25,50.2910,23.6211,51.9843,26.1119,2,Volyn
25,UKR,26,46.0728,34.1475,48.1090,37.2501,7,Zaporizhzhya
26,UKR,27,49.5837,27.1974,51.6978,29.7498,5,Zhytomyr

In [20]:
provinces.loc[(provinces['provinceID'] == 11)].iat[0,7]

'Kiev'

In [6]:
province_options = [{'label':row['province_name'],'value':row['provinceID']} for index,row in provinces.iterrows()]
province_options

[{'label': 'Cherkasy', 'value': 1},
 {'label': 'Chernihiv', 'value': 2},
 {'label': 'Chernivtsi', 'value': 3},
 {'label': 'Crimea', 'value': 4},
 {'label': 'Dnipropetrovsk', 'value': 5},
 {'label': 'Donetsk', 'value': 6},
 {'label': 'Ivano-Frankivsk', 'value': 7},
 {'label': 'Kharkiv', 'value': 8},
 {'label': 'Kherson', 'value': 9},
 {'label': 'Khmelnytskyy', 'value': 10},
 {'label': 'Kiev', 'value': 11},
 {'label': 'Kiev(City)', 'value': 12},
 {'label': 'Kirovohrad', 'value': 13},
 {'label': 'Luhansk', 'value': 14},
 {'label': 'Lviv', 'value': 15},
 {'label': 'Mykolayiv', 'value': 16},
 {'label': 'Odessa', 'value': 17},
 {'label': 'Poltava', 'value': 18},
 {'label': 'Rivne', 'value': 19},
 {'label': 'Sevastopol', 'value': 20},
 {'label': 'Sumy', 'value': 21},
 {'label': 'Ternopil', 'value': 22},
 {'label': 'Transcarpathia', 'value': 23},
 {'label': 'Vinnytsya', 'value': 24},
 {'label': 'Volyn', 'value': 25},
 {'label': 'Zaporizhzhya', 'value': 26},
 {'label': 'Zhytomyr', 'value': 27}]

In [7]:
week_options = [{'label':i,'value':i} for i in range(1,53,1)]
week_options[-1]

{'label': 52, 'value': 52}

In [12]:
import os
import re
from sys import stdout as out

def read_province_data(data_dir='../lab1/data', pattern='P[0-9]+-[0-9]+-[0-9]+.csv'):
    
    if not os.path.exists(data_dir): # Exit if the folder does not exist.
        out.write("Folder {} not found!\n".format(data_dir))
        return None
    
    regexp = re.compile(pattern)
    data_frame = pd.DataFrame()
    
    for name in (n for n in os.listdir(data_dir) if regexp.match(n)):
        file_path = os.path.join(data_dir, name)
        if os.path.isfile(file_path):
            out.write("Reading {}... ".format(name))

            # Detect province ID from the file name
            province_id = int(re.search('P([0-9]+)', name).group(1))
            
            # Read province data frame from the file
            province_frame = pd.read_csv(file_path, sep='[, ]+', engine='python', #index_col=[0,1],
                                         names=['Year','Week','SMN','SMT','VCI','TCI','VHI'])
            
            # Add column with province_id
            province_frame['Province'] = province_id
            
            # Append the resulting data frame
            data_frame = data_frame.append(province_frame)
            
            out.write("Province ID: {}\n".format(province_id))
    
    return data_frame

series = 'VHI'
province = 26
week_from = 2
week_to = 5
        
data_frame = read_province_data()
result_frame = data_frame.loc[(data_frame['Province'] == province)
                              & (data_frame['Week'] >= week_from)
                              & (data_frame['Week'] <= week_to),
                              ['Year', 'Week', series]]
result_frame

Reading P01-180308-213122.csv... Province ID: 1
Reading P02-180308-213122.csv... Province ID: 2
Reading P03-180308-213123.csv... Province ID: 3
Reading P04-180308-213124.csv... Province ID: 4
Reading P05-180308-213124.csv... Province ID: 5
Reading P06-180308-213125.csv... Province ID: 6
Reading P07-180308-213125.csv... Province ID: 7
Reading P08-180308-213126.csv... Province ID: 8
Reading P09-180308-213126.csv... Province ID: 9
Reading P10-180308-213127.csv... Province ID: 10
Reading P11-180308-213127.csv... Province ID: 11
Reading P12-180308-213128.csv... Province ID: 12
Reading P13-180308-213128.csv... Province ID: 13
Reading P14-180308-213129.csv... Province ID: 14
Reading P15-180308-213129.csv... Province ID: 15
Reading P16-180308-213130.csv... Province ID: 16
Reading P17-180308-213131.csv... Province ID: 17
Reading P18-180308-213131.csv... Province ID: 18
Reading P19-180308-213132.csv... Province ID: 19
Reading P20-180308-213132.csv... Province ID: 20
Reading P21-180308-213133.csv... Province ID: 21
Reading P22-180308-213133.csv... Province ID: 22
Reading P23-180308-213134.csv... Province ID: 23
Reading P24-180308-213134.csv... Province ID: 24
Reading P25-180308-213135.csv... Province ID: 25
Reading P26-180308-213136.csv... Province ID: 26
Reading P27-180308-213136.csv... Province ID: 27

     Year  Week    VHI
1    2014     2  39.69
2    2014     3  38.78
3    2014     4  38.50
4    2014     5  38.61
53   2015     2  42.02
54   2015     3  40.96
55   2015     4  41.71
56   2015     5  42.14
105  2016     2  38.95
106  2016     3  38.22
107  2016     4  37.60
108  2016     5  35.75
157  2017     2  61.64
158  2017     3  57.81
159  2017     4  53.66
160  2017     5  49.30